name: CI
on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint
      - name: format
        run: yarn format
      - name: commit format change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'refactor: prettier'
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install dependencies
        run: yarn
      - name: test
        uses: ArtiomTr/jest-coverage-report-action@v2
